var mvps = [{
    "year": "1931",
    "name": "Lefty Grove",
    "team": "Philadelphia Athletics",
    "position": "LHP",
    "wrc": 0,
    "wrcRank": 0
}, {
    "year": "1932",
    "name": "Jimmie Foxx",
    "team": "Philadelphia Athletics",
    "position": "1B",
    "opsRank": 1,
    "ops": "1.218",
    "warRank": 1,
    "war": "10.5",
    "rc": "202",
    "rcRank": 1,
    "rar": "115",
    "rarRank": 1,
    "waa": "8.0",
    "waaRank": 1,
    "wrc": 198,
    "wrcRank": 1
}, {
    "year": "1933",
    "name": "Jimmie Foxx",
    "team": "Philadelphia Athletics",
    "position": "1B",
    "opsRank": 1,
    "ops": "1.153",
    "warRank": 1,
    "war": "9.2",
    "rc": "180",
    "rcRank": 1,
    "rar": "99",
    "rarRank": 1,
    "waa": "6.9",
    "waaRank": 1,
    "wrc": 189,
    "wrcRank": 1
}, {
    "year": "1934",
    "name": "Mickey Cochrane",
    "team": "Detroit Tigers",
    "position": "C",
    "opsRank": 20,
    "ops": ".840",
    "warRank": 15,
    "war": "4.0",
    "rc": "77",
    "rcRank": 26,
    "rar": "42",
    "rarRank": 17,
    "waa": "2.1",
    "waaRank": 13,
    "wrc": 123,
    "wrcRank": 15
}, {
    "year": "1935",
    "name": "Hank Greenberg",
    "team": "Detroit Tigers",
    "position": "1B",
    "opsRank": 3,
    "ops": "1.039",
    "warRank": 4,
    "war": "7.7",
    "rc": "159",
    "rcRank": 1,
    "rar": "83",
    "rarRank": 4,
    "waa": "5.2",
    "waaRank": 4,
    "wrc": 158,
    "wrcRank": 3
}, {
    "year": "1936",
    "name": "Lou Gehrig",
    "team": "New York Yankees",
    "position": "1B",
    "opsRank": 1,
    "ops": "1.174",
    "warRank": 1,
    "war": "9.1",
    "rc": "189",
    "rcRank": 1,
    "rar": "105",
    "rarRank": 1,
    "waa": "6.8",
    "waaRank": 1,
    "wrc": 178,
    "wrcRank": 1
}, {
    "year": "1937",
    "name": "Charlie Gehringer",
    "team": "Detroit Tigers",
    "position": "2B",
    "opsRank": 9,
    "ops": ".978",
    "warRank": 4,
    "war": "7.4",
    "rc": "135",
    "rcRank": 4,
    "rar": "81",
    "rarRank": 4,
    "waa": "5.2",
    "waaRank": 4,
    "wrc": 145,
    "wrcRank": 6
}, {
    "year": "1938",
    "name": "Jimmie Foxx",
    "team": "Boston Red Sox",
    "position": "1B",
    "opsRank": 1,
    "ops": "1.166",
    "warRank": 1,
    "war": "7.6",
    "rc": "183",
    "rcRank": 1,
    "rar": "84",
    "rarRank": 1,
    "waa": "5.4",
    "waaRank": 1,
    "wrc": 173,
    "wrcRank": 1
}, {
    "year": "1939",
    "name": "Joe DiMaggio",
    "team": "New York Yankees",
    "position": "OF",
    "opsRank": 2,
    "ops": "1.119",
    "warRank": 1,
    "war": "8.1",
    "rc": "138",
    "rcRank": 3,
    "rar": "89",
    "rarRank": 1,
    "waa": "6.3",
    "waaRank": 1,
    "wrc": 180,
    "wrcRank": 2
}, {
    "year": "1940",
    "name": "Hank Greenberg",
    "team": "Detroit Tigers",
    "position": "OF",
    "opsRank": 1,
    "ops": "1.103",
    "warRank": 2,
    "war": "7.1",
    "rc": "166",
    "rcRank": 1,
    "rar": "75",
    "rarRank": 2,
    "waa": "5.0",
    "waaRank": 2,
    "wrc": 168,
    "wrcRank": 1
}, {
    "year": "1941",
    "name": "Joe DiMaggio",
    "team": "New York Yankees",
    "position": "OF",
    "opsRank": 2,
    "ops": "1.083",
    "warRank": 2,
    "war": "9.1",
    "rc": "152",
    "rcRank": 2,
    "rar": "94",
    "rarRank": 2,
    "waa": "7.1",
    "waaRank": 2,
    "wrc": 181,
    "wrcRank": 2
}, {
    "year": "1942",
    "name": "Joe Gordon",
    "team": "New York Yankees",
    "position": "2B",
    "opsRank": 4,
    "ops": ".900",
    "warRank": 2,
    "war": "8.2",
    "rc": "108",
    "rcRank": 4,
    "rar": "79",
    "rarRank": 2,
    "waa": "6.5",
    "waaRank": 2,
    "wrc": 152,
    "wrcRank": 3
}, {
    "year": "1943",
    "name": "Spud Chandler",
    "team": "New York Yankees",
    "position": "RHP",
    "wrc": 0,
    "wrcRank": 0
}, {
    "year": "1944",
    "name": "Hal Newhouser",
    "team": "Detroit Tigers",
    "position": "LHP",
    "wrc": 0,
    "wrcRank": 0
}, {
    "year": "1945",
    "name": "Hal Newhouser",
    "team": "Detroit Tigers",
    "position": "LHP",
    "wrc": 0,
    "wrcRank": 0
}, {
    "year": "1946",
    "name": "Ted Williams",
    "team": "Boston Red Sox",
    "position": "OF",
    "opsRank": 1,
    "ops": "1.164",
    "warRank": 1,
    "war": "10.9",
    "rc": "170",
    "rcRank": 1,
    "rar": "104",
    "rarRank": 1,
    "waa": "8.9",
    "waaRank": 1,
    "wrc": 215,
    "wrcRank": 1
}, {
    "year": "1947",
    "name": "Joe DiMaggio",
    "team": "New York Yankees",
    "position": "OF",
    "opsRank": 2,
    "ops": ".913",
    "warRank": 4,
    "war": "4.8",
    "rc": "109",
    "rcRank": 2,
    "rar": "47",
    "rarRank": 4,
    "waa": "3.0",
    "waaRank": 4,
    "wrc": 152,
    "wrcRank": 2
}, {
    "year": "1948",
    "name": "Lou Boudreau",
    "team": "Cleveland Indians",
    "position": "SS",
    "opsRank": 3,
    "ops": ".987",
    "warRank": 1,
    "war": "10.4",
    "rc": "135",
    "rcRank": 3,
    "rar": "107",
    "rarRank": 1,
    "waa": "8.5",
    "waaRank": 1,
    "wrc": 166,
    "wrcRank": 2
}, {
    "year": "1949",
    "name": "Ted Williams",
    "team": "Boston Red Sox",
    "position": "OF",
    "opsRank": 1,
    "ops": "1.141",
    "warRank": 1,
    "war": "9.1",
    "rc": "180",
    "rcRank": 1,
    "rar": "95",
    "rarRank": 1,
    "waa": "7.2",
    "waaRank": 1,
    "wrc": 186,
    "wrcRank": 1
}, {
    "year": "1950",
    "name": "Phil Rizzuto",
    "team": "New York Yankees",
    "position": "SS",
    "opsRank": 19,
    "ops": ".857",
    "warRank": 1,
    "war": "6.7",
    "rc": "111",
    "rcRank": 11,
    "rar": "71",
    "rarRank": 1,
    "waa": "4.7",
    "waaRank": 2,
    "wrc": 125,
    "wrcRank": 11
}, {
    "year": "1951",
    "name": "Yogi Berra",
    "team": "New York Yankees",
    "position": "C",
    "opsRank": 14,
    "ops": ".842",
    "warRank": 7,
    "war": "4.8",
    "rc": "92",
    "rcRank": 10,
    "rar": "48",
    "rarRank": 6,
    "waa": "3.0",
    "waaRank": 7,
    "wrc": 128,
    "wrcRank": 12
}, {
    "year": "1952",
    "name": "Bobby Shantz",
    "team": "Philadelphia Athletics",
    "position": "LHP",
    "wrc": 0,
    "wrcRank": 0
}, {
    "year": "1953",
    "name": "Al Rosen",
    "team": "Cleveland Indians",
    "position": "3B",
    "opsRank": 1,
    "ops": "1.034",
    "warRank": 1,
    "war": "10.1",
    "rc": "151",
    "rcRank": 1,
    "rar": "100",
    "rarRank": 1,
    "waa": "8.0",
    "waaRank": 1,
    "wrc": 178,
    "wrcRank": 1
}, {
    "year": "1954",
    "name": "Yogi Berra",
    "team": "New York Yankees",
    "position": "C",
    "opsRank": 8,
    "ops": ".855",
    "warRank": 6,
    "war": "5.3",
    "rc": "104",
    "rcRank": 5,
    "rar": "51",
    "rarRank": 6,
    "waa": "3.3",
    "waaRank": 6,
    "wrc": 137,
    "wrcRank": 8
}, {
    "year": "1955",
    "name": "Yogi Berra",
    "team": "New York Yankees",
    "position": "C",
    "opsRank": 17,
    "ops": ".819",
    "warRank": 9,
    "war": "4.5",
    "rc": "90",
    "rcRank": 11,
    "rar": "43",
    "rarRank": 9,
    "waa": "2.6",
    "waaRank": 9,
    "wrc": 122,
    "wrcRank": 17
}, {
    "year": "1956",
    "name": "Mickey Mantle",
    "team": "New York Yankees",
    "position": "OF",
    "opsRank": 1,
    "ops": "1.169",
    "warRank": 1,
    "war": "11.2",
    "rc": "188",
    "rcRank": 1,
    "rar": "116",
    "rarRank": 1,
    "waa": "9.3",
    "waaRank": 1,
    "wrc": 202,
    "wrcRank": 1
}, {
    "year": "1957",
    "name": "Mickey Mantle",
    "team": "New York Yankees",
    "position": "OF",
    "opsRank": 2,
    "ops": "1.177",
    "warRank": 1,
    "war": "11.3",
    "rc": "178",
    "rcRank": 1,
    "rar": "111",
    "rarRank": 1,
    "waa": "9.4",
    "waaRank": 1,
    "wrc": 217,
    "wrcRank": 2
}, {
    "year": "1958",
    "name": "Jackie Jensen",
    "team": "Boston Red Sox",
    "position": "OF",
    "opsRank": 5,
    "ops": ".931",
    "warRank": 7,
    "war": "4.9",
    "rc": "120",
    "rcRank": 3,
    "rar": "48",
    "rarRank": 6,
    "waa": "2.9",
    "waaRank": 9,
    "wrc": 150,
    "wrcRank": 6
}, {
    "year": "1959",
    "name": "Nellie Fox",
    "team": "Chicago White Sox",
    "position": "2B",
    "opsRank": 29,
    "ops": ".770",
    "warRank": 2,
    "war": "6.0",
    "rc": "97",
    "rcRank": 10,
    "rar": "60",
    "rarRank": 2,
    "waa": "4.0",
    "waaRank": 3,
    "wrc": 115,
    "wrcRank": 22
}, {
    "year": "1960",
    "name": "Roger Maris",
    "team": "New York Yankees",
    "position": "OF",
    "opsRank": 3,
    "ops": ".952",
    "warRank": 1,
    "war": "7.5",
    "rc": "111",
    "rcRank": 2,
    "rar": "74",
    "rarRank": 1,
    "waa": "5.7",
    "waaRank": 1,
    "wrc": 156,
    "wrcRank": 3
}, {
    "year": "1961",
    "name": "Roger Maris",
    "team": "New York Yankees",
    "position": "OF",
    "opsRank": 6,
    "ops": ".993",
    "warRank": 6,
    "war": "6.9",
    "rc": "138",
    "rcRank": 6,
    "rar": "72",
    "rarRank": 5,
    "waa": "4.8",
    "waaRank": 6,
    "wrc": 162,
    "wrcRank": 4
}, {
    "year": "1962",
    "name": "Mickey Mantle",
    "team": "New York Yankees",
    "position": "OF",
    "opsRank": 1,
    "ops": "1.091",
    "warRank": 2,
    "war": "5.9",
    "rc": "126",
    "rcRank": 2,
    "rar": "61",
    "rarRank": 1,
    "waa": "4.4",
    "waaRank": 1,
    "wrc": 192,
    "wrcRank": 1
}, {
    "year": "1963",
    "name": "Elston Howard",
    "team": "New York Yankees",
    "position": "C",
    "opsRank": 8,
    "ops": ".869",
    "warRank": 5,
    "war": "5.2",
    "rc": "83",
    "rcRank": 18,
    "rar": "50",
    "rarRank": 5,
    "waa": "3.6",
    "waaRank": 4,
    "wrc": 142,
    "wrcRank": 7
}, {
    "year": "1964",
    "name": "Brooks Robinson",
    "team": "Baltimore Orioles",
    "position": "3B",
    "opsRank": 7,
    "ops": ".889",
    "warRank": 1,
    "war": "8.1",
    "rc": "115",
    "rcRank": 5,
    "rar": "78",
    "rarRank": 1,
    "waa": "5.9",
    "waaRank": 2,
    "wrc": 145,
    "wrcRank": 6
}, {
    "year": "1965",
    "name": "Zoilo Versalles",
    "team": "Minnesota Twins",
    "position": "SS",
    "opsRank": 26,
    "ops": ".781",
    "warRank": 1,
    "war": "7.2",
    "rc": "102",
    "rcRank": 3,
    "rar": "67",
    "rarRank": 1,
    "waa": "5.1",
    "waaRank": 1,
    "wrc": 116,
    "wrcRank": 33
}, {
    "year": "1966",
    "name": "Frank Robinson",
    "team": "Baltimore Orioles",
    "position": "OF",
    "opsRank": 1,
    "ops": "1.047",
    "warRank": 1,
    "war": "7.7",
    "rc": "146",
    "rcRank": 1,
    "rar": "74",
    "rarRank": 1,
    "waa": "5.5",
    "waaRank": 1,
    "wrc": 195,
    "wrcRank": 1
}, {
    "year": "1967",
    "name": "Carl Yastrzemski",
    "team": "Boston Red Sox",
    "position": "OF",
    "opsRank": 1,
    "ops": "1.040",
    "warRank": 1,
    "war": "12.4",
    "rc": "155",
    "rcRank": 1,
    "rar": "112",
    "rarRank": 1,
    "waa": "10.2",
    "waaRank": 1,
    "wrc": 194,
    "wrcRank": 1
}, {
    "year": "1968",
    "name": "Denny McLain",
    "team": "Detroit Tigers",
    "position": "RHP",
    "wrc": 0,
    "wrcRank": 0
}, {
    "year": "1969",
    "name": "Harmon Killebrew",
    "team": "Minnesota Twins",
    "position": "3B",
    "opsRank": 2,
    "ops": "1.011",
    "warRank": 6,
    "war": "6.2",
    "rc": "146",
    "rcRank": 1,
    "rar": "60",
    "rarRank": 6,
    "waa": "3.8",
    "waaRank": 7,
    "wrc": 173,
    "wrcRank": 2
}, {
    "year": "1970",
    "name": "Boog Powell",
    "team": "Baltimore Orioles",
    "position": "1B",
    "opsRank": 3,
    "ops": ".962",
    "warRank": 14,
    "war": "5.1",
    "rc": "123",
    "rcRank": 3,
    "rar": "49",
    "rarRank": 14,
    "waa": "2.8",
    "waaRank": 15,
    "wrc": 160,
    "wrcRank": 2
}, {
    "year": "1971",
    "name": "Vida Blue",
    "team": "Oakland Athletics",
    "position": "LHP",
    "wrc": 0,
    "wrcRank": 0
}, {
    "year": "1972",
    "name": "Dick Allen",
    "team": "Chicago White Sox",
    "position": "1B",
    "opsRank": 1,
    "ops": "1.023",
    "warRank": 1,
    "war": "8.6",
    "rc": "131",
    "rcRank": 1,
    "rar": "74",
    "rarRank": 1,
    "waa": "6.2",
    "waaRank": 1,
    "wrc": 199,
    "wrcRank": 1
}, {
    "year": "1973",
    "name": "Reggie Jackson",
    "team": "Oakland Athletics",
    "position": "OF",
    "opsRank": 2,
    "ops": ".914",
    "warRank": 2,
    "war": "7.8",
    "rc": "112",
    "rcRank": 4,
    "rar": "73",
    "rarRank": 2,
    "waa": "5.6",
    "waaRank": 2,
    "wrc": 159,
    "wrcRank": 2
}, {
    "year": "1974",
    "name": "Jeff Burroughs",
    "team": "Texas Rangers",
    "position": "OF",
    "opsRank": 4,
    "ops": ".901",
    "warRank": 27,
    "war": "3.6",
    "rc": "113",
    "rcRank": 2,
    "rar": "34",
    "rarRank": 26,
    "waa": "1.3",
    "waaRank": 36,
    "wrc": 158,
    "wrcRank": 4
}, {
    "year": "1975",
    "name": "Fred Lynn",
    "team": "Boston Red Sox",
    "position": "OF",
    "opsRank": 1,
    "ops": ".967",
    "warRank": 2,
    "war": "7.4",
    "rc": "120",
    "rcRank": 2,
    "rar": "71",
    "rarRank": 2,
    "waa": "5.3",
    "waaRank": 2,
    "wrc": 161,
    "wrcRank": 2
}, {
    "year": "1976",
    "name": "Thurman Munson",
    "team": "New York Yankees",
    "position": "C",
    "opsRank": 24,
    "ops": ".769",
    "warRank": 11,
    "war": "5.3",
    "rc": "85",
    "rcRank": 17,
    "rar": "49",
    "rarRank": 11,
    "waa": "3.0",
    "waaRank": 12,
    "wrc": 126,
    "wrcRank": 23
}, {
    "year": "1977",
    "name": "Rod Carew",
    "team": "Minnesota Twins",
    "position": "1B",
    "opsRank": 1,
    "ops": "1.019",
    "warRank": 1,
    "war": "9.7",
    "rc": "160",
    "rcRank": 1,
    "rar": "97",
    "rarRank": 1,
    "waa": "7.4",
    "waaRank": 1,
    "wrc": 175,
    "wrcRank": 1
}, {
    "year": "1978",
    "name": "Jim Rice",
    "team": "Boston Red Sox",
    "position": "OF",
    "opsRank": 1,
    "ops": ".970",
    "warRank": 1,
    "war": "7.5",
    "rc": "147",
    "rcRank": 1,
    "rar": "72",
    "rarRank": 1,
    "waa": "5.2",
    "waaRank": 2,
    "wrc": 162,
    "wrcRank": 1
}, {
    "year": "1979",
    "name": "Don Baylor",
    "team": "California Angels",
    "position": "DH",
    "opsRank": 16,
    "ops": ".901",
    "warRank": 28,
    "war": "3.7",
    "rc": "126",
    "rcRank": 5,
    "rar": "38",
    "rarRank": 23,
    "waa": "1.4",
    "waaRank": 39,
    "wrc": 142,
    "wrcRank": 17
}, {
    "year": "1980",
    "name": "George Brett",
    "team": "Kansas City Royals",
    "position": "3B",
    "opsRank": 1,
    "ops": "1.118",
    "warRank": 1,
    "war": "9.4",
    "rc": "135",
    "rcRank": 1,
    "rar": "95",
    "rarRank": 1,
    "waa": "7.8",
    "waaRank": 1,
    "wrc": 198,
    "wrcRank": 1
}, {
    "year": "1981",
    "name": "Rollie Fingers",
    "team": "Milwaukee Brewers",
    "position": "RHP",
    "wrc": 0,
    "wrcRank": 0
}, {
    "year": "1982",
    "name": "Robin Yount",
    "team": "Milwaukee  Brewers",
    "position": "SS",
    "opsRank": 2,
    "ops": ".957",
    "warRank": 1,
    "war": "10.5",
    "rc": "136",
    "rcRank": 1,
    "rar": "106",
    "rarRank": 1,
    "waa": "8.4",
    "waaRank": 1,
    "wrc": 164,
    "wrcRank": 2
}, {
    "year": "1983",
    "name": "Cal Ripken",
    "team": "Baltimore Orioles",
    "position": "SS",
    "opsRank": 6,
    "ops": ".888",
    "warRank": 1,
    "war": "8.2",
    "rc": "120",
    "rcRank": 3,
    "rar": "80",
    "rarRank": 1,
    "waa": "6.0",
    "waaRank": 1,
    "wrc": 146,
    "wrcRank": 5
}, {
    "year": "1984",
    "name": "Willie Hernández",
    "team": "Detroit Tigers",
    "position": "LHP",
    "wrc": 0,
    "wrcRank": 0
}, {
    "year": "1985",
    "name": "Don Mattingly",
    "team": "New York Yankees",
    "position": "1B",
    "opsRank": 2,
    "ops": ".939",
    "warRank": 5,
    "war": "6.4",
    "rc": "136",
    "rcRank": 4,
    "rar": "65",
    "rarRank": 5,
    "waa": "4.3",
    "waaRank": 5,
    "wrc": 151,
    "wrcRank": 4
}, {
    "year": "1986",
    "name": "Roger Clemens",
    "team": "Boston Red Sox",
    "position": "RHP",
    "wrc": 0,
    "wrcRank": 0
}, {
    "year": "1987",
    "name": "George Bell",
    "team": "Toronto Blue  Jays",
    "position": "OF",
    "opsRank": 6,
    "ops": ".957",
    "warRank": 10,
    "war": "5.0",
    "rc": "125",
    "rcRank": 5,
    "rar": "51",
    "rarRank": 10,
    "waa": "2.8",
    "waaRank": 14,
    "wrc": 143,
    "wrcRank": 12
}, {
    "year": "1988",
    "name": "Jose Canseco",
    "team": "Oakland Athletics",
    "position": "OF",
    "opsRank": 2,
    "ops": ".959",
    "warRank": 4,
    "war": "7.2",
    "rc": "136",
    "rcRank": 2,
    "rar": "71",
    "rarRank": 4,
    "waa": "5.2",
    "waaRank": 4,
    "wrc": 169,
    "wrcRank": 1
}, {
    "year": "1989",
    "name": "Robin Yount",
    "team": "Milwaukee Brewers",
    "position": "OF",
    "opsRank": 3,
    "ops": ".896",
    "warRank": 6,
    "war": "5.8",
    "rc": "125",
    "rcRank": 1,
    "rar": "56",
    "rarRank": 6,
    "waa": "3.5",
    "waaRank": 6,
    "wrc": 149,
    "wrcRank": 3
}, {
    "year": "1990",
    "name": "Rickey Henderson",
    "team": "Oakland Athletics",
    "position": "OF",
    "opsRank": 1,
    "ops": "1.016",
    "warRank": 1,
    "war": "9.9",
    "rc": "137",
    "rcRank": 1,
    "rar": "97",
    "rarRank": 1,
    "waa": "7.9",
    "waaRank": 1,
    "wrc": 190,
    "wrcRank": 1
}, {
    "year": "1991",
    "name": "Cal Ripken",
    "team": "Baltimore Orioles",
    "position": "SS",
    "opsRank": 3,
    "ops": ".940",
    "warRank": 1,
    "war": "11.5",
    "rc": "134",
    "rcRank": 2,
    "rar": "113",
    "rarRank": 1,
    "waa": "9.2",
    "waaRank": 1,
    "wrc": 154,
    "wrcRank": 3
}, {
    "year": "1992",
    "name": "Dennis Eckersley",
    "team": "Oakland Athletics",
    "position": "RHP",
    "wrc": 0,
    "wrcRank": 0
}, {
    "year": "1993",
    "name": "Frank Thomas",
    "team": "Chicago White Sox",
    "position": "1B",
    "opsRank": 2,
    "ops": "1.033",
    "warRank": 9,
    "war": "6.2",
    "rc": "149",
    "rcRank": 2,
    "rar": "64",
    "rarRank": 8,
    "waa": "3.8",
    "waaRank": 10,
    "wrc": 170,
    "wrcRank": 2
}, {
    "year": "1994",
    "name": "Frank Thomas",
    "team": "Chicago White Sox",
    "position": "1B",
    "opsRank": 1,
    "ops": "1.217",
    "warRank": 3,
    "war": "6.3",
    "rc": "145",
    "rcRank": 1,
    "rar": "70",
    "rarRank": 3,
    "waa": "4.7",
    "waaRank": 3,
    "wrc": 205,
    "wrcRank": 1
}, {
    "year": "1995",
    "name": "Mo Vaughn",
    "team": "Boston Red Sox",
    "position": "1B",
    "opsRank": 9,
    "ops": ".963",
    "warRank": 15,
    "war": "4.3",
    "rc": "121",
    "rcRank": 6,
    "rar": "45",
    "rarRank": 15,
    "waa": "2.2",
    "waaRank": 18,
    "wrc": 139,
    "wrcRank": 12
}, {
    "year": "1996",
    "name": "Juan Gonzalez",
    "team": "Texas Rangers",
    "position": "OF",
    "opsRank": 9,
    "ops": "1.011",
    "warRank": 30,
    "war": "3.8",
    "rc": "126",
    "rcRank": 14,
    "rar": "39",
    "rarRank": 29,
    "waa": "1.8",
    "waaRank": 30,
    "wrc": 141,
    "wrcRank": 13
}, {
    "year": "1997",
    "name": "Ken Griffey",
    "team": "Seattle Mariners",
    "position": "OF",
    "opsRank": 2,
    "ops": "1.028",
    "warRank": 1,
    "war": "9.1",
    "rc": "152",
    "rcRank": 2,
    "rar": "94",
    "rarRank": 1,
    "waa": "6.7",
    "waaRank": 1,
    "wrc": 154,
    "wrcRank": 6
}, {
    "year": "1998",
    "name": "Juan Gonzalez",
    "team": "Texas Rangers",
    "position": "OF",
    "opsRank": 2,
    "ops": ".997",
    "warRank": 19,
    "war": "4.9",
    "rc": "134",
    "rcRank": 6,
    "rar": "51",
    "rarRank": 19,
    "waa": "2.6",
    "waaRank": 19,
    "wrc": 145,
    "wrcRank": 8
}, {
    "year": "1999",
    "name": "Ivan Rodriguez",
    "team": "Texas Rangers",
    "position": "C",
    "opsRank": 22,
    "ops": ".914",
    "warRank": 7,
    "war": "6.4",
    "rc": "102",
    "rcRank": 32,
    "rar": "68",
    "rarRank": 7,
    "waa": "4.2",
    "waaRank": 6,
    "wrc": 125,
    "wrcRank": 31
}, {
    "year": "2000",
    "name": "Jason Giambi",
    "team": "Oakland  Athletics",
    "position": "1B",
    "opsRank": 3,
    "ops": "1.123",
    "warRank": 4,
    "war": "7.7",
    "rc": "172",
    "rcRank": 2,
    "rar": "84",
    "rarRank": 3,
    "waa": "5.4",
    "waaRank": 4,
    "wrc": 183,
    "wrcRank": 1
}, {
    "year": "2001",
    "name": "Ichiro Suzuki",
    "team": "Seattle Mariners",
    "position": "OF",
    "opsRank": 39,
    "ops": ".838",
    "warRank": 4,
    "war": "7.7",
    "rc": "127",
    "rcRank": 9,
    "rar": "79",
    "rarRank": 4,
    "waa": "5.3",
    "waaRank": 4,
    "wrc": 124,
    "wrcRank": 26
}, {
    "year": "2002",
    "name": "Miguel Tejada",
    "team": "Oakland Athletics",
    "position": "SS",
    "opsRank": 24,
    "ops": ".861",
    "warRank": 7,
    "war": "5.6",
    "rc": "114",
    "rcRank": 12,
    "rar": "58",
    "rarRank": 7,
    "waa": "3.1",
    "waaRank": 8,
    "wrc": 129,
    "wrcRank": 20
}, {
    "year": "2003",
    "name": "Alex Rodriguez",
    "team": "Texas Rangers",
    "position": "SS",
    "opsRank": 3,
    "ops": ".995",
    "warRank": 1,
    "war": "8.4",
    "rc": "148",
    "rcRank": 2,
    "rar": "87",
    "rarRank": 1,
    "waa": "5.9",
    "waaRank": 1,
    "wrc": 151,
    "wrcRank": 4
}, {
    "year": "2004",
    "name": "Vladimir Guerrero",
    "team": "Anaheim Angels",
    "position": "OF",
    "opsRank": 4,
    "ops": ".989",
    "warRank": 6,
    "war": "5.6",
    "rc": "140",
    "rcRank": 1,
    "rar": "58",
    "rarRank": 5,
    "waa": "3.2",
    "waaRank": 8,
    "wrc": 154,
    "wrcRank": 4
}, {
    "year": "2005",
    "name": "Alex Rodriguez",
    "team": "New York Yankees",
    "position": "3B",
    "opsRank": 1,
    "ops": "1.031",
    "warRank": 1,
    "war": "9.4",
    "rc": "163",
    "rcRank": 1,
    "rar": "96",
    "rarRank": 1,
    "waa": "6.9",
    "waaRank": 1,
    "wrc": 174,
    "wrcRank": 1
}, {
    "year": "2006",
    "name": "Justin Morneau",
    "team": "Minnesota Twins",
    "position": "1B",
    "opsRank": 9,
    "ops": ".934",
    "warRank": 23,
    "war": "4.3",
    "rc": "125",
    "rcRank": 8,
    "rar": "44",
    "rarRank": 23,
    "waa": "2.0",
    "waaRank": 27,
    "wrc": 138,
    "wrcRank": 10
}, {
    "year": "2007",
    "name": "Alex Rodriguez",
    "team": "New York Yankees",
    "position": "3B",
    "opsRank": 1,
    "ops": "1.067",
    "warRank": 1,
    "war": "9.4",
    "rc": "166",
    "rcRank": 1,
    "rar": "98",
    "rarRank": 1,
    "waa": "7.0",
    "waaRank": 1,
    "wrc": 175,
    "wrcRank": 1
}, {
    "year": "2008",
    "name": "Dustin Pedroia",
    "team": "Boston Red Sox",
    "position": "2B",
    "opsRank": 26,
    "ops": ".869",
    "warRank": 2,
    "war": "6.9",
    "rc": "123",
    "rcRank": 4,
    "rar": "68",
    "rarRank": 2,
    "waa": "4.5",
    "waaRank": 3,
    "wrc": 127,
    "wrcRank": 26
}, {
    "year": "2009",
    "name": "Joe Mauer",
    "team": "Minnesota Twins",
    "position": "C",
    "opsRank": 1,
    "ops": "1.031",
    "warRank": 2,
    "war": "7.8",
    "rc": "138",
    "rcRank": 1,
    "rar": "80",
    "rarRank": 2,
    "waa": "5.7",
    "waaRank": 2,
    "wrc": 170,
    "wrcRank": 1
}, {
    "year": "2010",
    "name": "Josh Hamilton",
    "team": "Texas Rangers",
    "position": "OF",
    "opsRank": 2,
    "ops": "1.044",
    "warRank": 1,
    "war": "8.7",
    "rc": "134",
    "rcRank": 3,
    "rar": "85",
    "rarRank": 1,
    "waa": "6.7",
    "waaRank": 1,
    "wrc": 175,
    "wrcRank": 3
}, {
    "year": "2011",
    "name": "Justin Verlander",
    "team": "Detroit Tigers",
    "position": "RHP",
    "wrc": 0,
    "wrcRank": 0
}, {
    "year": "2012",
    "name": "Miguel Cabrera",
    "team": "Detroit Tigers",
    "position": "3B",
    "opsRank": 2,
    "ops": ".999",
    "warRank": 4,
    "war": "7.2",
    "rc": "139",
    "rcRank": 1,
    "rar": "71",
    "rarRank": 4,
    "waa": "4.7",
    "waaRank": 4,
    "wrc": 166,
    "wrcRank": 3
}, {
    "year": "2013",
    "name": "Miguel Cabrera",
    "team": "Detroit Tigers",
    "position": "3B",
    "opsRank": 1,
    "ops": "1.078",
    "warRank": 4,
    "war": "7.3",
    "rc": "155",
    "rcRank": 1,
    "rar": "71",
    "rarRank": 4,
    "waa": "5.2",
    "waaRank": 4,
    "wrc": 193,
    "wrcRank": 1
}, {
    "year": "2014",
    "name": "Mike Trout",
    "team": "Los Angeles Angels of Anaheim",
    "position": "OF",
    "opsRank": 3,
    "ops": ".939",
    "warRank": 1,
    "war": "7.9",
    "rc": "137",
    "rcRank": 1,
    "rar": "73",
    "rarRank": 1,
    "waa": "5.6",
    "waaRank": 1,
    "wrc": 167,
    "wrcRank": 1
}, {
    "year": "2015",
    "name": "Josh Donaldson",
    "team": "Toronto Blue Jays",
    "position": "3B",
    "opsRank": 3,
    "ops": ".939",
    "warRank": 2,
    "war": "8.8",
    "rc": "133",
    "rcRank": 2,
    "rar": "84",
    "rarRank": 2,
    "waa": "6.5",
    "waaRank": 2,
    "wrc": 154,
    "wrcRank": 4
}, {
    "year": "2016",
    "name": "Mike Trout",
    "team": "Los Angeles Angels of Anaheim",
    "position": "CF",
    "opsRank": 3,
    "ops": ".991",
    "warRank": 1,
    "war": "10.6",
    "rc": "148",
    "rcRank": 1,
    "rar": "104",
    "rarRank": 1,
    "waa": "8.2",
    "waaRank": 1,
    "wrc": 171,
    "wrcRank": 1
}]
